.PHONY: all clean

all: 1 2 3 4

clean:
	rm -rf 1 2 3 4

1: 1.cpp Makefile
	g++ -std=c++14 -o 1 1.cpp
	./1

2: 2.cpp Makefile
	g++ -std=c++14 -o 2 2.cpp
	./2

3: 3.cpp Makefile
	g++ -std=c++14 -o 3 3.cpp
	./3

4: 4.cpp Makefile
	g++ -std=c++14 -o 4 4.cpp
	./4
