cargo run --example 1
cargo run --example 2
cargo run --example 3
cargo run --example 4
cargo run --example 5_refactored
cargo run --example 6_refactored
cargo run --example 7
cargo run --example 8
cargo run --example 8_refactored
cargo run --example 9
cargo run --example 9_refactored
cargo run --example 10
cargo run --example 10_refactored
cargo run --example 11
cargo run --example 11_refactored
cargo run --example 12
cargo run --example 12_refactored
cargo run --example 13
cargo run --example 14
cargo run --example 15
cargo run --example 16
