.PHONY: all clean

all: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25

clean:
	rm -rf 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25

1: 1.cpp Makefile
	g++ -std=c++11 -o 1 1.cpp
	./1

2: 2.cpp Makefile
	g++ -std=c++11 -o 2 2.cpp
	./2

3: 3.cpp Makefile
	g++ -std=c++11 -o 3 3.cpp
	./3

4: 4.cpp Makefile
	g++ -std=c++11 -o 4 4.cpp
	./4

5: 5.cpp Makefile
	g++ -std=c++11 -o 5 5.cpp -lcrypto
	./5

6: 6.cpp Makefile
	g++ -std=c++11 -o 6 6.cpp
	./6

7: 7.cpp Makefile
	g++ -std=c++11 -o 7 7.cpp
	./7

8: 8.cpp Makefile
	g++ -std=c++11 -o 8 8.cpp
	./8

9: 9.cpp Makefile
	g++ -std=c++11 -o 9 9.cpp
	./9

10: 10.cpp Makefile
	g++ -std=c++11 -o 10 10.cpp
	./10

11: 11.cpp Makefile
	g++ -std=c++11 -o 11 11.cpp
	./11

12: 12.cpp Makefile
	g++ -std=c++11 -o 12 12.cpp
	./12

13: 13.cpp Makefile
	g++ -std=c++11 -o 13 13.cpp
	./13

14: 14.cpp Makefile
	g++ -std=c++11 -o 14 14.cpp -lcrypto
	./14

15: 15.cpp Makefile
	g++ -std=c++11 -o 15 15.cpp
	./15

16: 16.cpp Makefile
	g++ -std=c++11 -o 16 16.cpp
	./16

17: 17.cpp Makefile
	g++ -std=c++11 -o 17 17.cpp -lcrypto
	./17

18: 18.cpp Makefile
	g++ -std=c++11 -o 18 18.cpp
	./18

19: 19.cpp Makefile
	g++ -std=c++11 -o 19 19.cpp
	./19

20: 20.cpp Makefile
	g++ -std=c++11 -o 20 20.cpp
	./20

21: 21.cpp Makefile
	g++ -std=c++11 -o 21 21.cpp
	./21

22: 22.cpp Makefile
	g++ -std=c++11 -o 22 22.cpp
	./22

23: 23.cpp Makefile
	g++ -std=c++11 -o 23 23.cpp
	./23

24: 24.cpp Makefile
	g++ -std=c++11 -o 24 24.cpp
	./24

25: 25.cpp Makefile
	g++ -std=c++11 -o 25 25.cpp
	./25

