[package]
name = "aoc2020"
version = "0.1.0"
authors = ["kjohnson"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools="0.10.3"
pathfinding="3.0.4"
modinverse="0.1.1"
regex = "1.5.4"
structopt="0.3.25"
